### ISSUE TITLE
MMM-MusicOnDemand Eternal INITIALIZING...

### ISSUE THREAD

**Issue by Yeremiy** [ptrk95/MMM-MusicOnDemand#7]
Hey. Who will help? I always hev en Magic Mirror Initializing... hanging. I set showBrowser : true. In the browser it goes into the account, but initializing... still hangs. I suffer for a month. during this time two times appeared (Abs Deezer) Sorry for my bed english. 
-----------------------------------------------------------------------------------------**
Config module

{
module: "MMM-MusicOnDemand",
position: "top_right",
header: 'Music On Demand',
disabled: false,
config: {
//chromiumPath : "/home/pi/.config/chromium",
chromiumPath : "/usr/bin/chromium-browser",
// chromiumPath : null,
showCover : true,
//showBrowser : true,
//userDataDir : "/home/pi/.config/chromium"
email : ".............@hotmail.com",
password : "...............",
}
},
-----------------------------------------**
Nodejs ver v10.15.2
chromium-browser ver 74.0.3729.157
puppeteer ver 1.19.0
Raspberry PI 3 (Buster)
---------------------------------------------------------------------------------------------------------------------**
Thenks. Here are the errors:

`> magicmirror@2.8.0 start /home/pi/MagicMirror
> sh run-start.sh "mm" "debug9"

Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
No helper found for module: MMM-connection-status.
Initializing new module helper ...
Module helper loaded: MMM-SystemStats
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-MusicOnDemand
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-SystemStats
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-MusicOnDemand
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/---%40gmail.com/private-2bb3eb3ea76d0e38f5c3cdf9afb52f28/basic.ics - Interval: 300000
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/---%40group.calendar.google.com/private-1c289eafa2--------------------------------/basic.ics - Interval: 300000
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/es.spain%%40group.v.calendar.google.com/public/basic.ics - Interval: 300000
Create new news fetcher for url: https://www.abc.es/rss/feeds/abc_Madrid.xml - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: Hola!
[AMK2] GAction action package updates: Successfully pushed the app for the Assistant for testing
 
{ requestId: '--------0000-2015-98ba-94eb2c1cb0e0' } { profileFile: 'default.json', lang: 'es-ES' }
[AMK2] Device Action: { requestId: '--------0000-2015-98ba-94eb2c1cb0e0' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/FrameManager.js:1181:107)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onClosed (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/Connection.js:231:10)
    at Connection._onClose (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/Connection.js:121:15)
    at WebSocketTransport._ws.addEventListener.event (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/WebSocketTransport.js:45:22)
    at WebSocket.onClose (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.emitClose (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (events.js:182:13)
  -- ASYNC --
    at Frame.<anonymous> (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.goto (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/Page.js:624:49)
    at Page.<anonymous> (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/helper.js:145:23)
    at LoginDeezer (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_helper.js:97:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[HOTWORD] Detected: snowboy
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'snowboy', file: null }
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Transcription: qué hora es  --- Done: false
[AMK2] end-of-utterance
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Stopping module helper: MMM-SystemStats
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword
Error: Protocol error: Connection closed. Most likely the page has been closed.
    at assert (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/helper.js:278:11)
    at Page.close (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/Page.js:944:5)
    at Page.<anonymous> (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/helper.js:145:23)
    at closeBrowser (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_helper.js:74:20)
    at Class.stop (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_helper.js:62:3)
    at App.stop (/home/pi/MagicMirror/js/app.js:247:16)
    at App.app.on (/home/pi/MagicMirror/js/electron.js:110:7)
    at App.emit (events.js:182:13)
    at Object.exports.execute (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item-roles.js:272:19)
    at MenuItem.click (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:54:16)
  -- ASYNC --
    at Page.<anonymous> (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/helper.js:144:27)
    at closeBrowser (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_helper.js:74:20)
    at Class.stop (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_helper.js:62:3)
    at App.stop (/home/pi/MagicMirror/js/app.js:247:16)
    at App.app.on (/home/pi/MagicMirror/js/electron.js:110:7)
    at App.emit (events.js:182:13)
    at Object.exports.execute (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item-roles.js:272:19)
    at MenuItem.click (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:54:16)
    at Function.executeCommand (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu.js:31:13)`

**Comment by Yeremiy** [comment]
Config module

{
	             module: "MMM-MusicOnDemand",
		     position: "top_right",
                     header: 'Music On Demand',
		     disabled: false,
		     config: {   
                                //chromiumPath : "/home/pi/.config/chromium",
				chromiumPath : "/usr/bin/chromium-browser",
				// chromiumPath : null,
				showCover : true,
                                //showBrowser : true,
                                //userDataDir : "/home/pi/.config/chromium"
				email : "superviki13@hotmail.com",
				password : "viking13viking",
				}
		 },
Nodejs ver v10.15.2
chromium-browser ver 74.0.3729.157 
puppeteer ver 5.8.0
puppeteer-core ver 5.8.0
Raspberry PI 3 (Buster)

**Comment by Yeremiy** [comment]
Found it:
Releases per Chromium Version:
Chromium 77.0.3803.0 - Puppeteer v1.19.0
Chromium 76.0.3803.0 - Puppeteer v1.17.0
Chromium 75.0.3765.0 - Puppeteer v1.15.0
Chromium 74.0.3723.0 - Puppeteer v1.13.0
Chromium 73.0.3679.0 - Puppeteer v1.12.2

lowered version Puppeteer to 1.13.0 (my chromium this 74.0.3729), did not help

**Comment by toy31** [comment]
It's working with
Chromium: 72.0.3626
Puppeteer: 1.11.0
