### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by easy20192018** [ptrk95/MMM-MusicOnDemand#9]
Hello.
 The module a not working. Chromium-browser closed connection.
Showbrowser = true. Its show Cover but no playback the Music.

My Hardware is Raspberry PI 3B
Chromium-browser version is 74.0.3729.157
OS Raspbian 10

MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
Use existing news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml
Use existing news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml
Use existing news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml
{ TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r706915
    at Timeout.onTimeout (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/Launcher.js:359:14)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) name: 'TimeoutError' }
{ TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r706915
    at Timeout.onTimeout (/home/pi/MagicMirror/modules/MMM-MusicOnDemand/node_modules/puppeteer/lib/Launcher.js:359:14)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) name: 'TimeoutError' }

**Comment by toy31** [comment]
It's working with
Chromium: 72.0.3626
Puppeteer: 1.11.0
